---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false

  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-prod.c45wii2n9a2c.eu-central-1.rds.amazonaws.com
    TYPEORM_PORT: 5532
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: udapeople123
    TYPEORM_DATABASE: udapeople-prod 

  roles:
    - configure-prometheus-node-exporter
    - configure-server
